apiVersion: v1
kind: Service
metadata:
  name: arcadebackend
  labels:
    name: arcadebackend  
spec:
  selector:
    name: arcadebackend  
  type: LoadBalancer
  ports:
   - port: 80
     name: arcadebackend
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadebackend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: arcadebackend      
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: arcadebackend        
    spec:
      imagePullSecrets:
        - name: acr-secret
      # imagePullSecrets:
      #   - name: teamregistry
      containers:
      - name: arcadebackend
        image: t34m8acree9720.azurecr.io/gamebot/metal:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: arcadebackend         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "FF_BETS"
            value: "1"
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 1
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   failureThreshold: 1